### ISSUE TITLE
Divide by 0 error in PSO

### ISSUE THREAD

**Issue by deanrp2** [mradaideh/neorl#25]
I encountered this error:
![image](https://user-images.githubusercontent.com/37961031/154094240-fce75284-621f-47a9-b526-b4b09f5f6651.png)

When looking at the code for `neorl/evolu/pso.py`

It looks like on lines 366 and 367, the population solutions are sorted and then the best is assigned to ` self.swm_pos`. Then, in line 253 of `self.UpdateParticle`, this `self.swm_pos` is used for some kind of division.

I think the problem is that if the best member perfectly hits that 0.00000 a divide by zero error is encountered. I am honestly not sure if this is correct.

**Comment by deanrp2** [comment]
Also, this only occurs in `globw`

**Comment by mradaideh** [comment]
@deanrp2 Thank you for pointing out to this potential flaw in this PSO mode. Indeed, when the local fitness of the swarm approaches zero, the division by zero prevents calculating an inertia weight (`w`) for the next generation. This is indeed a flaw in how `w` is calculated by the original algorithm published here: https://doi.org/10.1155/DDNS/2006/79295.

However, since it is difficult to tell whether zero is a global minima for this problem or it is just a local value found by the optimizer, when a division by zero occurs, then the value of `w` is determined by drawing a random value between 0.1 and 0.9. Here 0.1 shows more exploitation and 0.9 is more exploration. We expect this situation to happen occasionally or even rately during the search so randomness here is just to escape this division by zero issue. Thanks again for finding this problem.
